title: Hedge-born
description: An OSR RPG made by me.
theme: just-the-docs

url: https://PixelCaldera.github.io/Hedge-born

aux_links:
  Template Repository: https://github.com/PixelCaldera/Hedge-born

search_enabled: true